[package]
description = "Macros for writing fat contract sidevm program"
edition = "2021"
keywords = ["fat-contract", "pink", "ink", "sidevm"]
license = "Apache-2.0"
name = "pink-sidevm-macro"
version = "0.1.0"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2 = "1.0"
syn = {version = "1.0", features = ["full", "visit-mut", "extra-traits", "parsing"]}

[dev-dependencies]
insta = "1.14.0"
rustfmt-snippet = {version = "0.1.0", path = "../../../rustfmt-snippet/"}
