[global]
address = "0.0.0.0"
port = 8000
workers = 1

[global.limits]
json = 104857600
bytes = 104857600
"PhactoryAPI.DispatchBlocks" = 104857600
"PhactoryAPI.InitRuntime" = 104857600

[default.shutdown]
ctrlc = false
