[package]
name = "sfq-test"
version = "0.1.0"
edition = "2021"

[dependencies]
rocket = "0.5.0"
phala-scheduler = { path = "../../crates/phala-scheduler" }
clap = { version = "4.0.32", features = ["derive"] }
