[package]
name = "pherry"
version = "0.1.2"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
env_logger = "0.9.0"
futures = { package = "futures", version = "0.3.4" }
log = "0.4"
tokio = { version = "1.20.3", features = ["full"] }
reqwest = { version = "0.11" }
hex = { version = "*" }
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
clap = { version = "4.0.19", features = ["derive"] }

async-trait = "0.1.57"
system = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", package = "frame-system" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", package = "sp-runtime" }
sp-finality-grandpa = { package = "sp-finality-grandpa", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33", default-features = false }
codec = { package = 'parity-scale-codec', version = "3.0" }
scale-info = { version = '2.0' }

pallet-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
pallet-indices = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.33" }

phala-types = { path = "../../crates/phala-types" }
phala-pallets = { path = "../../pallets/phala" }
phala-trie-storage = { path = "../../crates/phala-trie-storage" }
phala-node-rpc-ext = { path = "../../crates/phala-node-rpc-ext" }
phala-mq = { path = "../../crates/phala-mq" }
phactory-api = { path = "../../crates/phactory/api", features = ["pruntime-client"] }

phaxt = { path = "../../crates/phaxt" }
