[package]
name = "pherry"
version = "0.1.2"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.69"
env_logger = "0.9.0"
futures = { package = "futures", version = "0.3.4" }
log = "0.4"
tokio = { version = "1.24.2", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks"] }
hex = "0.4.3"
base64 = "0.13.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
rand = "0.8.4"
clap = { version = "4.0.32", features = ["derive"] }

async-trait = "0.1.57"
system = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", package = "frame-system" }
sp-core = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
sp-runtime = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", package = "sp-runtime" }
sp-consensus-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0", default-features = false }
codec = { package = 'parity-scale-codec', version = "3.3" }
scale-info = { version = '2.3' }

pallet-grandpa = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
pallet-indices = { git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }
balances = { package = "pallet-balances", git = "https://github.com/paritytech/polkadot-sdk.git", branch = "release-polkadot-v1.1.0" }

phala-types = { path = "../../crates/phala-types" }
phala-pallets = { path = "../../pallets/phala" }
phala-trie-storage = { path = "../../crates/phala-trie-storage" }
phala-node-rpc-ext = { path = "../../crates/phala-node-rpc-ext" }
phala-mq = { path = "../../crates/phala-mq" }
phactory-api = { path = "../../crates/phactory/api", features = ["pruntime-client"] }

phaxt = { path = "../../crates/phaxt" }
async-stream = "0.3.4"
