[workspace]

[package]
edition = "2021"
name = "sideprog"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
log = "0.4.16"
once_cell = "1.10.0"
sidevm = "0.1"
tokio = { version = "1", features = ["macros", "io-util"] }
futures = "0.3"
log_buffer = "1.0"
hex_fmt = "0.3.0"
hyper = { version = "0.14.18", features = ["server", "http1"] }
chrono = { version = "0.4.22" }
scale = { package = "parity-scale-codec", version = "3" }
serde_json = "1"
serde = { version = "1", features = ["derive"] }

[dev-dependencies]
insta = "1.21.0"