[package]
name = "pink-extension"
version = "0.4.1"
edition = "2018"
description = "Phala's ink! for writing fat contracts"
license = "Apache-2.0"
keywords = ["fat-contract", "pink", "ink"]

[dependencies]
ink = { version = "4", default-features = false, features = ["ink-debug"] }
scale = { package = "parity-scale-codec", version = "3.1", default-features = false, features = ["derive"] }
scale-info = { version = "2.1", default-features = false, features = ["derive"], optional = true }
pink-extension-macro = { version = "0.4.0", path = "./macro" }
log = "0.4.17"

[dev-dependencies]
insta = "1.7.2"

[features]
default = ["std", "runtime_utils", "ink-as-dependency"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
]
runtime_utils = ["std"]
ink-as-dependency = []
