[package]
name = "pink-extension"
version = "0.1.4"
edition = "2018"
description = "Phala's ink! for writing fat contracts"
license = "Apache-2.0"
keywords = ["fat-contract", "pink", "ink"]

[dependencies]
ink_primitives = { version = "3.0.0-rc8", default-features = false }
ink_metadata = { version = "3.0.0-rc8", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc8", default-features = false }
ink_storage = { version = "3.0.0-rc8", default-features = false }
ink_lang = { version = "3.0.0-rc8", default-features = false }

scale = { package = "parity-scale-codec", version = "3.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"], optional = true }
pink-extension-macro = { version = "0.1.0", path = "./macro" }

[dev-dependencies]
insta = "1.7.2"

[features]
default = ["std", "runtime_utils"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
]
runtime_utils = ["std"]
ink-as-dependency = []
