[package]
name = "pink-extension"
version = "0.4.6"
edition = "2018"
description = "Phala's ink! for writing phat contracts"
license = "Apache-2.0"
keywords = ["phat-contract", "pink", "ink"]

[dependencies]
ink = { version = "4.2", default-features = false, features = ["ink-debug"] }
scale = { package = "parity-scale-codec", version = "3.3", default-features = false, features = ["derive"] }
scale-info = { version = "2.3", default-features = false, features = ["derive"], optional = true }
pink-extension-macro = { version = "0.4.2", path = "./macro" }
log = "0.4.17"
dlmalloc = { version = "0.2.4", default-features = false, features = ["global"], optional = true }
this-crate = { version = "0.1", path = "../../this-crate" }
num_enum = { version = "0.6", default-features = false }

[dev-dependencies]
insta = "1.7.2"

[features]
default = ["std", "runtime_utils", "ink-as-dependency"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "num_enum/std",
]
runtime_utils = ["std"]
dlmalloc = ["ink/no-allocator", "dep:dlmalloc"]
ink-as-dependency = []
