[package]
name = "pink-macro"
version = "0.4.5"
edition = "2018"
description = "Macros for writing phat contract"
license = "Apache-2.0"
keywords = ["phat-contract", "pink", "ink"]

[lib]
proc-macro = true

[dependencies]
ink_ir = { version = "4.2", default-features = false }
syn = { version = "2.0", features = ["full", "visit-mut", "extra-traits", "parsing"] }
quote = "1.0"
proc-macro2 = "1.0"
proc-macro-crate = "1.0.0"
unzip3 = "1"
heck = "0.4.0"

[dev-dependencies]
rustfmt-snippet = "0.1"
insta = "1"
