[workspace]
[package]
edition = "2021"
name = "sidevm-host"
version = "0.1.0"

[dependencies]
sidevm-host-runtime = { path = "../host-runtime", features = [
    "wasmer-compiler-cranelift",
] }
tokio = { version = "1.17.0", features = ["full"] }
log = "0.4"
tracing-subscriber = "0.3"
anyhow = "1.0.69"
clap = { version = "4.0.32", features = ["derive"] }
once_cell = "1"
rocket = "0.5.0"
scale = { package = "parity-scale-codec", version = "3.6.5" }
sp-core = "21"
