[package]
edition = "2021"
name = "pruntime"
version = "0.1.0"

[profile.release]
panic = "abort"

[dependencies]
anyhow = "1.0"
colored = "2"
http_req = {version = "0.8.1", default-features = false, features = ["rust-tls"]}
libc = "0.2"
log = "0.4.14"
num_cpus = "1.13"
os_pipe = "1.0.0"
rocket = "0.4.7"
rocket_codegen = "0.4.5"
rocket_cors = "0.5.2"
serde_json = "1.0"
structopt = "0.3.21"

base64 = "0.13.0"

env_logger = {version = "0.9.0", default-features = false, features = ["termcolor"]}
lazy_static = {version = "1.4.0", default-features = false}
parity-scale-codec = {version = "3.0", default-features = false}
rocket_contrib = {version = "0.4.5", features = ["json"]}
serde = {version = "1.0", default-features = false, features = ["derive"]}
urlencoding = "2.1.0"

phactory = {path = "../../../crates/phactory"}
phactory-api = {path = "../../../crates/phactory/api"}
phactory-pal = {path = "../../../crates/phactory/pal"}
phala-allocator = {path = "../../../crates/phala-allocator"}

[patch.crates-io]
# TODO.kevin.must:
# This is a bad workaround for https://github.com/gramineproject/gramine/issues/341
# Remove this patch once the upstream fixed
hyper = {git = "https://github.com/kvinwang/hyper.git", branch = "no-timeout"}
