[package]
name = "phala-blockchain-runtime"
version = "2.0.0"
authors = ["Jasl"]
edition = "2018"

[dependencies]
aura = { version = "2.0.0", default-features = false, package = "pallet-aura", path = "../../substrate/frame/aura" }
balances = { version = "2.0.0", default-features = false, package = "pallet-balances", path = "../../substrate/frame/balances" }
frame-support = { version = "2.0.0", default-features = false, path = "../../substrate/frame/support" }
grandpa = { version = "2.0.0", default-features = false, package = "pallet-grandpa", path = "../../substrate/frame/grandpa" }
indices = { version = "2.0.0", default-features = false, package = "pallet-indices", path = "../../substrate/frame/indices" }
randomness-collective-flip = { version = "2.0.0", default-features = false, package = "pallet-randomness-collective-flip", path = "../../substrate/frame/randomness-collective-flip" }
sudo = { version = "2.0.0", default-features = false, package = "pallet-sudo", path = "../../substrate/frame/sudo" }
system = { version = "2.0.0", default-features = false, package = "frame-system", path = "../../substrate/frame/system" }
timestamp = { version = "2.0.0", default-features = false, package = "pallet-timestamp", path = "../../substrate/frame/timestamp" }
transaction-payment = { version = "2.0.0", default-features = false, package = "pallet-transaction-payment", path = "../../substrate/frame/transaction-payment" }

codec = { package = "parity-scale-codec", version = "1.0.0", default-features = false, features = ["derive"] }
frame-executive = { version = "2.0.0", default-features = false, path = "../../substrate/frame/executive" }
safe-mix = { version = "1.0.0", default-features = false }
serde = { version = "1.0.101", optional = true, features = ["derive"] }
sp-api = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/api" }
sp-block-builder = { path = "../../substrate/primitives/block-builder", default-features = false}
sp-consensus-aura = { version = "0.8", default-features = false, path = "../../substrate/primitives/consensus/aura" }
sp-core = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/core" }
sp-inherents = { path = "../../substrate/primitives/inherents", default-features = false}
sp-io = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/io" }
sp-offchain = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/offchain" }
sp-runtime = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/runtime" }
sp-session = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/session" }
sp-std = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/std" }
sp-transaction-pool = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/transaction-pool" }
sp-version = { version = "2.0.0", default-features = false, path = "../../substrate/primitives/version" }

chrono = { version = "0.4", default-features = false, features = ["serde"] }
itertools = { version = "0.8", default-features = false }
untrusted = { version = "0.7" }
base64 = { version = "0.11", default-features = false, features = ["alloc"] }
hex = { version = "0.4", default-features = false }
webpki = { path = "../../webpki", default_features = false }
ring = { path = "../../ring", default_features = false, features = ["alloc"] }
# serde_json_core = {}


[build-dependencies]
wasm-builder-runner = { version = "1.0.4", package = "substrate-wasm-builder-runner", path = "../../substrate/utils/wasm-builder-runner" }

[features]
default = ["std", "include-wasm"]
std = [
	"aura/std",
	"balances/std",
	"codec/std",
	"frame-executive/std",
	"frame-support/std",
	"grandpa/std",
	"indices/std",
	"randomness-collective-flip/std",
	"safe-mix/std",
	"serde",
	"sp-api/std",
	"sp-block-builder/std",
	"sp-consensus-aura/std",
	"sp-core/std",
	"sp-inherents/std",
	"sp-io/std",
	"sp-offchain/std",
	"sp-runtime/std",
	"sp-session/std",
	"sp-std/std",
	"sp-transaction-pool/std",
	"sp-version/std",
	"sudo/std",
	"system/std",
	"timestamp/std",
	"transaction-payment/std",
]
include-wasm = []
