[package]
description = "Mock pink chain extension for Phala pink contract"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
name = "pink-chain-extension"
version = "0.5.1"
edition = "2021"

[dependencies]
pink = { version = "0.5.0", path = "../pink" }
reqwest-env-proxy = { version = "0.1", path = "../../reqwest-env-proxy" }
sp-core = { version = "21", features = ["full_crypto"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks", "trust-dns"] }
log = "0.4"
getrandom = "0.2"
once_cell = "1.10.0"
hex_fmt = "0.3.0"
futures = "0.3"
tokio = { version = "1", features = ["full"] }
