[package]
name = "node-executor"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
description = "Substrate node implementation in Rust."
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0" }
scale-info = { version = "2.0", features = ["derive"] }
node-primitives = { path = "../../substrate/bin/node/primitives" }
node-runtime = { package = "phala-node-runtime", path = "../runtime" }
sc-executor = { path = "../../substrate/client/executor" }
sp-core = { path = "../../substrate/primitives/core" }
sp-keystore = { path = "../../substrate/primitives/keystore" }
sp-state-machine = { path = "../../substrate/primitives/state-machine" }
sp-trie = { path = "../../substrate/primitives/trie" }
frame-benchmarking = { path = "../../substrate/frame/benchmarking" }

[dev-dependencies]
criterion = "0.3.0"
frame-support = { path = "../../substrate/frame/support" }
frame-system = { path = "../../substrate/frame/system" }
# node-testing = { version = "2.0.0", path = "../testing" }
pallet-balances = { path = "../../substrate/frame/balances" }
pallet-contracts = { path = "../../substrate/frame/contracts" }
pallet-im-online = { path = "../../substrate/frame/im-online" }
pallet-timestamp = { path = "../../substrate/frame/timestamp" }
pallet-treasury = { path = "../../substrate/frame/treasury" }
sp-application-crypto = { path = "../../substrate/primitives/application-crypto" }
sp-consensus-babe = { path = "../../substrate/primitives/consensus/babe" }
sp-runtime = { path = "../../substrate/primitives/runtime" }
sp-externalities = { path = "../../substrate/primitives/externalities" }
wat = "1.0"
futures = "0.3.9"

[features]
wasmtime = ["sc-executor/wasmtime"]
wasmi-errno = ["sc-executor/wasmi-errno"]
stress-test = []

[[bench]]
name = "bench"
harness = false
