[package]
name = "app"
version = "0.2.4"
authors = ["jasl"]
build = "build.rs"
edition = "2018"

[dependencies]
sgx_types = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
sgx_urts  = { rev = "v1.1.3", git = "https://github.com/apache/teaclave-sgx-sdk.git" }
mio       = "0.7"
num_cpus = "1.13.0"
libc = "0.2"
structopt = "0.3.21"

rocket = { version = "0.5.0-rc.1", features = ["json"] }
rocket_cors = "0.6.0-alpha1"
serde     = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
lazy_static = "1.1.0"
log = "0.4"
env_logger = "0.8"
hex = "0.4.2"
colored = "2"
phactory-api = { path = "../../../crates/phactory/api" }
parity-scale-codec = { version = "2.2", features = ["full"] }
phala-rocket-middleware = { path = "../../../crates/phala-rocket-middleware" }

[dev-dependencies]
ring-compat = "0.0.1"
base64 = "0.12.3"
hex-literal = "0.3.1"

[patch.'https://github.com/apache/teaclave-sgx-sdk.git']
# sgx_alloc = { path = "../../../teaclave-sgx-sdk" }
# sgx_backtrace = { path = "../../../teaclave-sgx-sdk" }
# sgx_backtrace_sys = { path = "../../../teaclave-sgx-sdk" }
# sgx_build_helper = { path = "../../../teaclave-sgx-sdk" }
# sgx_cov = { path = "../../../teaclave-sgx-sdk" }
# sgx_crypto_helper = { path = "../../../teaclave-sgx-sdk" }
# sgx_demangle = { path = "../../../teaclave-sgx-sdk" }
# sgx_libc = { path = "../../../teaclave-sgx-sdk" }
# sgx_rand = { path = "../../../teaclave-sgx-sdk" }
# sgx_rand_derive = { path = "../../../teaclave-sgx-sdk" }
# sgx_serialize = { path = "../../../teaclave-sgx-sdk" }
# sgx_serialize_derive = { path = "../../../teaclave-sgx-sdk" }
# sgx_serialize_derive_internals = { path = "../../../teaclave-sgx-sdk" }
# sgx_tcrypto = { path = "../../../teaclave-sgx-sdk" }
# sgx_tcrypto_helper = { path = "../../../teaclave-sgx-sdk" }
# sgx_tdh = { path = "../../../teaclave-sgx-sdk" }
# sgx_tkey_exchange = { path = "../../../teaclave-sgx-sdk" }
# sgx_tprotected_fs = { path = "../../../teaclave-sgx-sdk" }
# sgx_trts = { path = "../../../teaclave-sgx-sdk" }
# sgx_tse = { path = "../../../teaclave-sgx-sdk" }
# sgx_tseal = { path = "../../../teaclave-sgx-sdk" }
# sgx_tstd = { path = "../../../teaclave-sgx-sdk" }
# sgx_tunittest = { path = "../../../teaclave-sgx-sdk" }
sgx_types = { path = "../../../teaclave-sgx-sdk/sgx_types" }
# sgx_ucrypto = { path = "../../../teaclave-sgx-sdk" }
# sgx_unwind = { path = "../../../teaclave-sgx-sdk" }
sgx_urts = { path = "../../../teaclave-sgx-sdk/sgx_urts" }
