[workspace]
[package]
name = "log_server"
version = "0.1.2"
authors = ["[your_name] <[your_email]>"]
edition = "2018"
resolver = "2"

[package.metadata.cargo-machete]
ignored = ["ink", "scale", "scale-info"]

[dependencies]
ink = { version = "4", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }

pink-extension = { default-features = false, path = "../../pink/pink-extension" }
this-crate = { path = "../../this-crate" }

[build-dependencies]
run_shell = "0.1"
sp-core = "21"

[lib]
name = "log_server"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
]
ink-as-dependency = []
