[package]
description = "Macros for writing phat contract sidevm program"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
edition = "2021"
keywords = ["phat-contract", "pink", "ink", "sidevm"]
name = "sidevm-macro"
version = "0.2.0-alpha.3"

[lib]
proc-macro = true

[dependencies]
proc-macro-crate = "1.0.0"
proc-macro2 = "1.0"
syn = { version = "1.0", features = ["full", "visit-mut", "extra-traits", "parsing"] }
heck = "0.4.0"

[dev-dependencies]
insta = "1.14.0"
rustfmt-snippet = { version = "0.1.0" }
