[package]
name = "node-rpc"
version = "2.0.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "Apache-2.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
jsonrpc-core = "18.0"
node-primitives = { path = "../../substrate/bin/node/primitives" }
pallet-transaction-payment-rpc = { path = "../../substrate/frame/transaction-payment/rpc/" }
sc-client-api = { path = "../../substrate/client/api" }
sc-consensus-babe = { path = "../../substrate/client/consensus/babe" }
sc-consensus-babe-rpc = { path = "../../substrate/client/consensus/babe/rpc" }
sc-consensus-epochs = { path = "../../substrate/client/consensus/epochs" }
sc-chain-spec = { path = "../../substrate/client/chain-spec" }
sc-finality-grandpa = { path = "../../substrate/client/finality-grandpa" }
sc-finality-grandpa-rpc = { path = "../../substrate/client/finality-grandpa/rpc" }
sc-keystore = { path = "../../substrate/client/keystore" }
sc-rpc-api = { path = "../../substrate/client/rpc-api" }
sc-rpc = { path = "../../substrate/client/rpc" }
sc-sync-state-rpc = { path = "../../substrate/client/sync-state-rpc" }
sp-api = { path = "../../substrate/primitives/api" }
sp-block-builder = { path = "../../substrate/primitives/block-builder" }
sp-blockchain = { path = "../../substrate/primitives/blockchain" }
sp-keystore = { path = "../../substrate/primitives/keystore" }
sp-consensus = { path = "../../substrate/primitives/consensus/common" }
sp-consensus-babe = { path = "../../substrate/primitives/consensus/babe" }
sp-runtime = { path = "../../substrate/primitives/runtime" }
sc-transaction-pool-api = { path = "../../substrate/client/transaction-pool/api" }
substrate-frame-rpc-system = { path = "../../substrate/utils/frame/rpc/system" }
