[package]
name = "pink-kv-session"
version = "0.2.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"
description = "KV session primitives for phat off-chain rollup"

[dependencies]

[dev-dependencies]
scale = { package = "parity-scale-codec", version = "3.6.5" }
