[package]
name = "justification-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
phactory = { path = "../../crates/phactory" }
phactory-api = { path = "../../crates/phactory/api" }
pherry = { path = "../pherry" }

log = "0.4.14"
anyhow = "1.0.43"
clap = { version = "4.0.19", features = ["derive"] }
env_logger = "0.9.0"
scale = { package = 'parity-scale-codec', version = "3.1" }
crossbeam = "0.8.2"
