[package]
name = "justification-validate"
version = "0.1.0"
edition = "2021"

[dependencies]
phactory = { path = "../../crates/phactory" }
phactory-api = { path = "../../crates/phactory/api" }
pherry = { path = "../pherry" }

log = "0.4.14"
anyhow = "1.0.69"
clap = { version = "4", features = ["derive"] }
env_logger = "0.9.0"
scale = { package = 'parity-scale-codec', version = "2" }
crossbeam = "0.8.2"
tokio = { version = "1", features = ["full"] }
reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "socks", "json"] }
serde = "1.0"
serde_json = "1.0"
