[package]
name = "phala-async-executor"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-std = "1.10.0"
async-executor = "1.4.1"
futures = "0.3.17"

[features]
default = []
no-thread = []