[package]
name = "pink-utils"
version = "0.1.0"
edition = "2021"
description = "Useful utilities for pink"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
keywords = ["fat-contract", "pink", "ink"]

[dependencies]
ink_prelude = { version = "3.4.0", default-features = false }
ink_primitives = { version = "3.4.0", default-features = false }
ink_metadata = { version = "3.4.0", default-features = false, features = ["derive"], optional = true }
ink_storage = { version = "3.4.0", default-features = false }
ink_lang = { version = "3.4.0", default-features = false }
ink_env = { version = "3.4.0", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

pink-extension = { version = "0.1.14", default-features = false, path = "../../pink/pink-extension" }
hex = { version = "0.4.3", default-features = false, features = ["alloc"] }

[dev-dependencies]
pink-extension-runtime = "0.1.3"

[features]
default = ["std"]
std = [
    "ink_primitives/std",
    "ink_metadata/std",
    "ink_storage/std",
    "ink_env/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
]
