[package]
name = "pink-utils"
version = "0.5.0"
edition = "2021"
description = "Useful utilities for pink"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
keywords = ["phat-contract", "pink", "ink"]

[dependencies]
ink = { version = "4", default-features = false }

scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }

pink = { version = "0.5.0", default-features = false, path = "../../pink/pink" }

[dev-dependencies]
pink-chain-extension = { path = "../../pink/chain-extension" }

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink/std",
]
