[package]
name = "substrate-subxt-client"
version = "0.4.0"
authors = ["David Craven <david@craven.ch>", "Parity Technologies <admin@parity.io>"]
edition = "2018"

license = "GPL-3.0"
repository = "https://github.com/paritytech/substrate-subxt"
documentation = "https://docs.rs/substrate-subxt-client"
homepage = "https://www.parity.io/"
description = "Embed a substrate node into your subxt application."
keywords = ["parity", "substrate", "blockchain"]

[dependencies]
async-std = "1.6.4"
futures = { version = "0.3.5", features = ["compat"] }
futures01 = { package = "futures", version = "0.1.29" }
jsonrpsee = "0.1.0"
log = "0.4.11"
sc-network = { version = "0.8.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
sc-service = { version = "0.8.0", default-features = false, git = "https://github.com/paritytech/substrate", branch = "master" }
serde_json = "1.0.57"
sp-keyring = { version = "2.0.0", git = "https://github.com/paritytech/substrate", branch = "master" }
thiserror = "1.0.20"

[dev-dependencies]
async-std = { version = "1.6.4", features = ["attributes"] }
env_logger = "0.7.1"
substrate-subxt = { path = ".." }
tempdir = "0.3.7"
test-node = { path = "../test-node" }
