[package]
description = "A logger works in sidevm guest program"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
edition = "2021"
name = "sidevm-logger"
version = "0.1.1"

[dependencies]
log = { version = "0.4.16", features = ["std"] }
sidevm-env = { version = "0.1.0", path = "../env" }
