[package]
name = "headers-cache"
version = "0.1.1"
edition = "2021"

[dependencies]
pherry = { path = "../pherry" }

log = "0.4.14"
anyhow = "1.0.43"
clap = { version = "4.0.19", features = ["derive"] }
tokio = { version = "1.9.0", features = ["full"] }
chrono = { version = "0.4.22" }
env_logger = "0.9.0"
rocket = "0.5.0-rc.2"
scale = { package = 'parity-scale-codec', version = "3.1" }
rocksdb = { version = "0.19.0", default-features = false, features = ["snappy", "jemalloc"] } # aligned with kvdb-rocksdb
serde = { version = "1", features = ["derive"] }
serde_json = "1"
phala-rocket-middleware = { path = "../../crates/phala-rocket-middleware" }
