[package]
name = "mqproxy"
authors = ["Kevin Wang <wy721@qq.com>"]
version = "0.1.0"
edition = "2018"
resolver = "2"

# workaround for https://github.com/rust-lang/cargo/issues/6745
[workspace]

[dependencies]
ink_primitives = { version = "3.0.0-rc3", default-features = false }
ink_metadata = { version = "3.0.0-rc3", default-features = false, features = ["derive"], optional = true }
ink_env = { version = "3.0.0-rc3", default-features = false }
ink_storage = { version = "3.0.0-rc3", default-features = false }
ink_lang = { version = "3.0.0-rc3", default-features = false }

scale = { package = "parity-scale-codec", version = "3.0", default-features = false, features = ["derive"] }
scale-info = { version = "2.0", default-features = false, features = ["derive"], optional = true }
pink-extension = { version="0.1.0", default-features = false, features = ["ink-as-dependency"] }

[lib]
name = "mqproxy"
path = "lib.rs"
crate-type = [
	"cdylib", "lib",
]

[features]
default = ["std"]
std = [
    "ink_metadata/std",
    "ink_env/std",
    "ink_storage/std",
    "ink_primitives/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
]
ink-as-dependency = []
