[package]
authors = ['Phala Network']
edition = '2018'
name = 'pallet-mining-staking'
version = "1.0.0"
license = "Apache 2.0"
homepage = "https://phala.network/"
repository = "https://github.com/Phala-Network/phala-blockchain"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { package = "parity-scale-codec", version = "2.1", default-features = false, features = ["derive", "max-encoded-len"] }
itertools = { version = "0.8", default-features = false }
frame-support = { default-features = false, path = "../../substrate/frame/support" }
frame-system = { default-features = false, path = "../../substrate/frame/system" }
sp-runtime = { default-features = false, path = "../../substrate/primitives/runtime" }
sp-std = { default-features = false, path = "../../substrate/primitives/std" }
sp-io = { default-features = false, path = "../../substrate/primitives/io" }
sp-core = { default-features = false, path = "../../substrate/primitives/core" }
log = { version = "0.4.14", default-features = false }

phala-pallets = { default-features = false, path = "../phala" }
pallet-balances = { default-features = false, path = "../../substrate/frame/balances" }

[dev-dependencies]
frame-support-test = { version = "3.0.0", path = "../../substrate/frame/support/test" }
pallet-timestamp = { version = "3.0.0", path = "../../substrate/frame/timestamp" }

[features]
default = ['std']
std = [
    "codec/std",
    "sp-runtime/std",
    "frame-support/std",
    "frame-system/std",
    "sp-io/std",
    "sp-std/std",
    "sp-core/full_crypto",
    "phala-pallets/std",
    "pallet-balances/std",
    "log/std"
]
try-runtime = ["frame-support/try-runtime"]
