[package]
name = "experimental-node"
version = "2.0.0"
authors = ["Jasl"]
build = "build.rs"
edition = "2018"

[[bin]]
name = "experimental-node"
path = "src/main.rs"

[dependencies]
derive_more = "0.15.0"
futures = "0.1.29"
ctrlc = { version = "3.1.3", features = ["termination"] }
log = "0.4.8"
tokio = "0.1.22"
exit-future = "0.1.4"
parking_lot = "0.9.0"
codec = { package = "parity-scale-codec", version = "1.0.0" }
trie-root = "0.15.2"
sr-io = { path = "../substrate/primitives/sr-io" }
substrate-cli = { path = "../substrate/client/cli" }
primitives = { package = "substrate-primitives", path = "../substrate/primitives/core" }
substrate-executor = { path = "../substrate/client/executor" }
substrate-service = { path = "../substrate/client/service" }
inherents = { package = "substrate-inherents", path = "../substrate/primitives/inherents" }
transaction-pool = { package = "substrate-transaction-pool", path = "../substrate/client/transaction-pool" }
network = { package = "substrate-network", path = "../substrate/client/network" }
aura = { package = "substrate-consensus-aura", path = "../substrate/client/consensus/aura" }
aura-primitives = { package = "substrate-consensus-aura-primitives", path = "../substrate/primitives/consensus/aura" }
grandpa = { package = "substrate-finality-grandpa", path = "../substrate/client/finality-grandpa" }
grandpa-primitives = { package = "substrate-finality-grandpa-primitives", path = "../substrate/primitives/finality-grandpa" }
substrate-client = {  path = "../substrate/client/" }
runtime = { package = "experimental-node-runtime", path = "runtime" }
sr-primitives = { path = "../substrate/primitives/sr-primitives" }
basic-authorship = { package = "substrate-basic-authorship", path  = "../substrate/client/basic-authorship"}

[build-dependencies]
vergen = "3.0.4"
build-script-utils = { package = "substrate-build-script-utils", path = "../substrate/utils/build-script-utils" }

