[package]
name = "check_system"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"

[profile.release.package.compiler_builtins]
debug-assertions = false
overflow-checks = false

[dependencies]
ink = { version = "4", default-features = false }

scale = { package = "parity-scale-codec", version = "3", default-features = false, features = ["derive"] }
scale-info = { version = "2", default-features = false, features = ["derive"], optional = true }

pink-extension = { version = "0.4", default-features = false, path = "../../../crates/pink/pink-extension" }
phat_js = { version = "0.1.5", default-features = false }

[dependencies.indeterministic_functions]
version = "0.1"
default-features = false
path = "../indeterministic_functions"
features = ["ink-as-dependency"]

[build-dependencies]
sp-core = "7"

[lib]
name = "check_system"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "phat_js/std",
    "scale-info/std",
    "pink-extension/std",
    "indeterministic_functions/std",
]
ink-as-dependency = []
