# workaround for https://github.com/rust-lang/cargo/issues/6745
[workspace]

[package]
edition = "2021"
name = "sidevm-host"
version = "0.1.0"

[dependencies]
pink-sidevm-host-runtime = { path = "../../host-runtime", features = [
    "wasmer-compiler-cranelift",
] }
tokio = { version = "1.17.0", features = ["full"] }
log = "0.4"
env_logger = "0.9.0"
anyhow = "1.0.56"
clap = { version = "3", features = ["derive"] }
once_cell = "1"
rocket = "0.5.0-rc.2"
scale = { package = "parity-scale-codec", version = "3" }
hex = "0.4.3"
