[package]
edition = "2021"
name = "sidevm-host"
version = "0.1.0"

[dependencies]
pink-sidevm-host-runtime = {path = "../../host-runtime"}
tokio = {version = "1.17.0", features = ["full"]}
env_logger = "0.9.0"
anyhow = "1.0.56"
