[package]
description = "The low level protocol between sidevm guest and host"
homepage = "https://github.com/Phala-Network/phala-blockchain"
license = "Apache-2.0"
edition = "2021"
name = "sidevm-env"
version = "0.2.0-alpha.4"

[dependencies]
sidevm-macro = { version = "0.2.0-alpha.3", path = "../macro" }

cfg-if = "1.0.0"
derive_more = "0.99.17"
num_enum = "0.5.7"
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = [
    "derive",
    "std",
] }
tinyvec = { version = "1.5.1", features = ["alloc"] }
log = "0.4.16"
futures = "0.3"

[features]
host = []
