[package]
edition = "2021"
name = "pink-sidevm-env"
version = "0.1.0"

[dependencies]
pink-sidevm-macro = {path = "../macro", version = "0.1.0"}

cfg-if = "1.0.0"
derive_more = "0.99.17"
num_enum = "0.5.7"
once_cell = "1.10.0"
scale = {package = "parity-scale-codec", version = "3", default-features = false, features = ["derive", "std"]}
tinyvec = {version = "1.5.1", features = ["alloc"]}

[features]
host = []
