[package]
name = "sidevm_deployer"
version = "0.1.0"
authors = ["[your_name] <[your_email]>"]
edition = "2021"
description = "This is a demo describes how to write a pink driver contract"

[dependencies]
ink = { version = "4", default-features = false }
scale = { package = "parity-scale-codec", version = "3.6.5", default-features = false, features = ["derive"] }
scale-info = { version = "2.10.0", default-features = false, features = ["derive"], optional = true }

pink-extension = { default-features = false, path = "../../pink/pink-extension" }
system = { version = "1.0", default-features = false, path = "../system" }
this-crate = { path = "../../this-crate" }

[lib]
name = "sidevm_deployer"
path = "lib.rs"

[features]
default = ["std"]
std = [
    "ink/std",
    "scale/std",
    "scale-info/std",
    "pink-extension/std",
    "system/std",
]
ink-as-dependency = []
