[package]
name = "debug-cli"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11"
codec = { package = "parity-scale-codec", version = "3.1" }
hex = "0.4"
clap = { version = "4.0.19", features = ["derive"] }
anyhow = "1.0.43"

sp-runtime = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sp-core = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
frame-support = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }
sc-finality-grandpa = { git = "https://github.com/paritytech/substrate", branch = "polkadot-v0.9.34" }

phala-types = { path = "../../crates/phala-types" }
phala-pallets = { path = "../../pallets/phala" }
phactory-api = { path = "../../crates/phactory/api", features = ["pruntime-client"] }
phala-crypto = { path = "../../crates/phala-crypto" }

tokio = { version = "1.20.3", features = ["full"] }
