[package]
name = "debug-cli"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11"
codec = { package = "parity-scale-codec", version = "2.0.0" }
hex = "0.4"
structopt = "0.3"

phala-types = { path = "../../common/types" }
