[package]
name = "debug-cli"
version = "0.1.0"
authors = ["h4x3rotab <h4x3rotab@gmail.com>"]
edition = "2018"

[dependencies]
base64 = "0.11"
codec = { package = "parity-scale-codec", version = "3.0" }
hex = "0.4"
clap = { version = "3", features = ["derive"] }
anyhow = "1.0.43"

sp-runtime = { path = "../../substrate/primitives/runtime" }
sp-core = { path = "../../substrate/primitives/core" }
frame-support = { path = "../../substrate/frame/support" }
sc-finality-grandpa = { path = "../../substrate/client/finality-grandpa" }

phala-types = { path = "../../crates/phala-types" }
phala-pallets = { path = "../../pallets/phala" }
phactory-api = { path = "../../crates/phactory/api", features = ["pruntime-client"] }
phactory = { path = "../../crates/phactory" }
phala-crypto = { path = "../../crates/phala-crypto" }

tokio = { version = "1.10.0", features = ["full"] }
